### ISSUE TITLE
Introduction Wizard

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube-Meta#11]
# Related Changes

- This will replace #6.
- On general startup, the Messages tab shall be shown by default.

# Behavior

- On first-time startup, this introduction wizard shall be displayed.
- When the user skips/exits the wizard, the current tab should be... current.

# Steps

- **This is the tab for contacts**
- Tap this button to import a public key
- **This is the tab for messages log**
- Compose messages here
- Interpret messages here
- **This is the tab for private keys**
- Tap this to generate or import a keypair
- Do you want to create or import a keypair right now?

# iOS

![Wizard - S1](https://user-images.githubusercontent.com/2139261/59195582-e0302280-8b7b-11e9-99fb-e888cd5a1056.png)
![Wizard - S2](https://user-images.githubusercontent.com/2139261/59195583-e0302280-8b7b-11e9-971f-26737c81a05b.png)
![Wizard - S3](https://user-images.githubusercontent.com/2139261/59195584-e0302280-8b7b-11e9-9da3-3d22aec31414.png)
![Wizard - S4](https://user-images.githubusercontent.com/2139261/59195586-e0c8b900-8b7b-11e9-9acd-0d70c8778108.png)
![Wizard - S5](https://user-images.githubusercontent.com/2139261/59195589-e0c8b900-8b7b-11e9-8d1b-e64441b4a200.png)
![Wizard - S6](https://user-images.githubusercontent.com/2139261/59195591-e0c8b900-8b7b-11e9-8dda-d84b94d77001.png)
![Wizard - S7](https://user-images.githubusercontent.com/2139261/59195593-e1614f80-8b7b-11e9-9e21-f33ed1f480ea.png)
![Wizard - S8](https://user-images.githubusercontent.com/2139261/59195594-e1f9e600-8b7b-11e9-8188-48e776d7845b.png)

# Android

# Common Image Assets

![arrow-up](https://user-images.githubusercontent.com/2139261/59196018-0efac880-8b7d-11e9-820c-9252e728eb7e.png)
![arrow-1t3](https://user-images.githubusercontent.com/2139261/59196019-0f935f00-8b7d-11e9-95aa-5cb48bd1da7a.png)
![arrow-2t4](https://user-images.githubusercontent.com/2139261/59196023-0f935f00-8b7d-11e9-93d3-7c8caf45f890.png)

**Comment by Tedko** [comment]
@jk234ert @MainasuK @neruthes 
We'll have a offline meetup for users in the 1st week of July. Expect this introduction can be delivered 1 week before that (mid-June).

**Comment by neruthes** [comment]
Expect iOS draft today.

**Comment by Tedko** [comment]
looks cool. 
Whats you guys opinion about the '+' button reuse

**Comment by neruthes** [comment]
> looks cool.
> Whats you guys opinion about the '+' button reuse

Create an issue in Tessercube-Talk for that.

**Comment by neruthes** [comment]
> looks cool.
> Whats you guys opinion about the '+' button reuse

You already opened https://github.com/DimensionDev/Tessercube-Meta/issues/29

**Comment by Tedko** [comment]
@jk234ert

Let me know the update tmr.

**Comment by jk234ert** [comment]
@Tedko 
I'm working on this, target to complete before the end of 19th.

**Comment by jk234ert** [comment]
Code implementation almost done.
Anyone could help traditional Chinese translation?
@neruthes is there any changes of guide text in English?

**Comment by Tedko** [comment]
Upload the i18n(Or xml/txt?) file here. I will let Miao do the Traditional
Chinese translation this week.

**Comment by jk234ert** [comment]
i18n file (here)[https://github.com/DimensionDev/Tessercube-iOS/blob/feat/NewIntroWizard/TesserCube/Resources/en.lproj/Localizable.strings]

Line NO.: 37 ~ 47

**Comment by jk234ert** [comment]
Internal testers could update to 1.0.4(1) to test the implementation.

- The introduction wizard displays every time user navigates to the main "TabBar" view (e.g. first time launch app, or go back from a deeper view)

After code being approved, I'll modify the mechanism to make the wizard only displays the **first time** app launches.

**Comment by Tedko** [comment]
The internal test ver looks good to me.

**Comment by jk234ert** [comment]
> The internal test ver looks good to me.
> […](#)

I'll release beta version after translation being ready.

**Comment by Tedko** [comment]
This is completed on iOS side and looks fine. Check Android and maybe close this one.

**Comment by neruthes** [comment]
Looks like already completed. Reopen if I misunderstood.
