### ISSUE TITLE
Report bug within the App

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-Meta#12]
Intuitive place/way to report bug or send feedback to us

**Comment by jk234ert** [comment]
In upcoming Tessercube iOS TestFlight release, users could shake to invoke a "Report Issue" button at anywhere inside the app. Click the button will open [Tessercube iOS issue](https://github.com/DimensionDev/Tessercube-iOS/issues) in a new webview.

**Comment by Tedko** [comment]
看到有了。但是手机上github直接要求先登录…

这个讨论下吧 宁愿发邮件的。不然反馈流程太长了。

**Comment by Tedko** [comment]
另外 是不是需要加一个setting 区域。 这个joy看一下。

**Comment by neruthes** [comment]
GitHub Issues is pretty good enough for now. Priority rests elsewhere.

**Comment by Tedko** [comment]
In general: should we use email instead of GitHub repo link on phone? GitHub require login first. Let’s better keep the bug reporting easier for users.

**Comment by Tedko** [comment]
rather use the email

**Comment by neruthes** [comment]
If so, we need an IssuesBot which accepts emails and automatically create issues out of the email content.

**Comment by Tedko** [comment]
> If so, we need an IssuesBot which accepts emails and automatically create issues out of the email content.

MS App Center is a working solution for Android version now. will check the possibility soon.
