### ISSUE TITLE
Using words that make user easier to understand the relationship between contacts and keys

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-Meta#16]
Users without knowledge about PGP will be confused about the relationship between keys and contacts. For example: https://www.reddit.com/r/Maskbook/comments/bjs8ss/adding_ime_tessercube_keyboard/?utm_source=share&utm_medium=ios_app (the user is unable to figure out my pub key acts as my id or my cell numbers/nickname)

After click ‘Contacts’ -- ‘+’ button, it asks users the public key and ‘import keypairs’. This is very confusing for normal users, since they cannot associate ‘pub key’ with ‘contacts’. Even Keybase or Miji, they have an ID system (keybase: based on its centralized id and other service ; Miji: random generated words such as ‘GoodWillLong’ represents some mathematical mapping of keys, but keep the centralized ‘key registry’ for key/id lookup)

We need use words ppl can understand 1st, and also build a decentralized id system, (maybe like Eth Name service?). Such as mapping the pubkey into some human memorable words?

**Comment by neruthes** [comment]
Will be scheduled.
