### ISSUE TITLE
CRLF vs CR vs LF

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube-Meta#17]
I just want to make sure if the OpenPGP standard has specified which linebreak should be used, and if specified, are we abiding to it right now in our implementations.

**Comment by Tedko** [comment]
P.S.: Crypto Lib/implementation in both platform is the same.

**Comment by neruthes** [comment]
Seems that there is no longer any problem with linebreak? cc @Tlaster @MainasuK

**Comment by neruthes** [comment]
Orally confirmed. No longer a problem.
