### ISSUE TITLE
Introduction Video: How to use keyboard within other App

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-Meta#18]
Need to be Platform Specific.

Also need to Explain the meaning of '🔑 '   & '🔒 ' button in the keyboard etc.

DDL: May 11

**Comment by neruthes** [comment]
More discussion needed before determining priority.

**Comment by Tedko** [comment]
example of confused user with PGP experience: ![Image](https://i.imgur.com/VoUWXc2.jpg)

**Comment by Tedko** [comment]
@neruthes hows the discussion outcome for intro/or Wizard timeline

**Comment by neruthes** [comment]
> @neruthes hows the discussion outcome for intro/or Wizard timeline

Will start when you come back.
