### ISSUE TITLE
Remove "Interpret" button in Keyboard

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube-Meta#23]

**Comment by neruthes** [comment]
<img width="1368" alt="Screen Shot 2019-05-14 at 06 40 42" src="https://user-images.githubusercontent.com/2139261/57676078-3c526600-7613-11e9-8879-3ecc10ad45e4.png">
<img width="895" alt="Screen Shot 2019-05-14 at 06 40 04" src="https://user-images.githubusercontent.com/2139261/57676087-3e1c2980-7613-11e9-9ff9-ffcbf15ebe00.png">

**Comment by yisiliu** [comment]
Do we still keep the **copy to interpret** in keyboard interface?

**Comment by neruthes** [comment]
> Do we still keep the **copy to interpret** in keyboard interface?

Sure. Now we kill nothing more than this particular button.

**Comment by neruthes** [comment]
Sketch updated in both places.

**Comment by Tlaster** [comment]
0.2.5-pre4

2019年5月15日 上午12:54，"Neruthes (a.k.a. J.N.)" <notifications@github.com>写道：

Assigned #23<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDimensionDev%2FTessercube-Meta%2Fissues%2F23&data=02%7C01%7C%7C422fc1d26ab24b23a9f408d6d88cdf62%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636934496879075216&sdata=iSsG41H3i%2Fh9p31uof%2B6mijFvt7LHcgqCYsdmQw7xP8%3D&reserved=0> to @Tlaster<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTlaster&data=02%7C01%7C%7C422fc1d26ab24b23a9f408d6d88cdf62%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636934496879085229&sdata=EKXiqYpxEjDO4cbLLY2tH392fOoWl8AuJPeKjg6POR8%3D&reserved=0>.

―

**Comment by Tedko** [comment]
Released on both platform. No problem found.
