### ISSUE TITLE
Add i18n for zh-Hant

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube-Meta#25]
Expected release: 2019 May 17 20:00.

No accuracy required for this time. Using machine translation is okay.

**Comment by Tlaster** [comment]
- [x] en-US
- [x] zh-CN
- [x] zh-TW (11 days ago)
- [x] ja-JP (11 days ago)
- [x] ko-KR (6 days ago)

**Comment by neruthes** [comment]
Done on both platforms.

👍
