### ISSUE TITLE
Expert options on keygen

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube-Meta#3]
# iOS

![Me - Create Key](https://user-images.githubusercontent.com/2139261/56640377-62af6200-6662-11e9-9110-f8115a376ba7.png)

# Android

<img width="953" alt="Screen Shot 2019-05-06 at 05 49 40" src="https://user-images.githubusercontent.com/2139261/57208347-dcc8da80-6fc2-11e9-9793-202a002f6f50.png">

# Easy Mode

Turned on by default.

Easy Mode can be turned off.

If Easy Mode is turned off, expert options may appear.

# Default Settings

Algorithm: ECC (SECP256K1)

# Expert Options

Fields: 

- Algorithm
- Key Length

The two fields are supposed to be like date pickers, or drop down menu in the context of iPad (if are going to support iPad soon).

Not always does Key Length appear. If the algorithm does not support key length configuration, the field shall be hidden.

# Algorithms

For now, we support:

- ECC (SECP256K1)
- RSA

# Key Length Options

Possible key length options:

- ECC:
  - No option
- RSA:
  - 4096
  - 3072 (recommended)
  - 2048

# Notes

These settings are not remembered for the next time.

By turning on “Publish Public Key”, it is uploaded to a few selected key servers including Ubuntu and MIT.

**Comment by yisiliu** [comment]
1. The easy mode should be turned on in default, as designed
2. We should also discuss the password requirement
3. How should we publish the key and where to?

**Comment by neruthes** [comment]
> * The easy mode should be turned on in default, as designed
> * We should also discuss the password requirement
> * How should we publish the key and where to?

Details added.

**Comment by yisiliu** [comment]
We should also add private key backup schemes for both RSA and ECC

**Comment by neruthes** [comment]
Visual draft for Android added.

**Comment by neruthes** [comment]
Done on both platforms?

**Comment by jk234ert** [comment]
Done.
