### ISSUE TITLE
Cannot display full message if the msg is long

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-Meta#32]
Update:

<img width="804" alt="Screen Shot 2019-06-12 at 03 48 59" src="https://user-images.githubusercontent.com/6687437/59301791-07463b80-8cc5-11e9-83ae-69552355c69d.png">

Need figure out a way to read the msg within keyboard etc

<img width="625" alt="Screen Shot 2019-05-31 at 20 07 11" src="https://user-images.githubusercontent.com/6687437/58704937-3cf34680-83e0-11e9-82c5-0dcc5559e0b5.png">

Users have problem to read long message since it cannot be fully displayed.

**Comment by Tedko** [comment]
Fixed on iOS side

**Comment by neruthes** [comment]
Should be a bug report.

**Comment by Tedko** [comment]
@Tlaster

**Comment by neruthes** [comment]
Should be a bug report.
