### ISSUE TITLE
[iOS] Make search box in Contacts tab persistent regardless of pageYOffset, like in Contacts app

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube-Meta#34]
![0DF25190-DFC0-4963-A15F-D96CB6F4F9A2](https://user-images.githubusercontent.com/2139261/59263491-ae2cc800-8c30-11e9-94f2-603290ac576e.png)

![0DF25190-DFC0-4963-A15F-D96CB6F4F9A3](https://user-images.githubusercontent.com/2139261/59263892-7f632180-8c31-11e9-96d0-81281e8bae61.PNG)

**Comment by jk234ert** [comment]
fixed by [#10](https://github.com/DimensionDev/Tessercube-iOS/pull/10)

**Comment by neruthes** [comment]
> fixed by [#10](https://github.com/DimensionDev/Tessercube-iOS/pull/10)

👍
