### ISSUE TITLE
Messages History: Divide into 2 timelines

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube-Meta#5]
<img width="496" alt="Screen Shot 2019-04-24 at 17 07 46" src="https://user-images.githubusercontent.com/2139261/56678995-8058e780-66b3-11e9-9d1c-5c7c71c7538e.png">

Note that a draft will disappear if it is finished by the user, either by marking it as finished or by tapping "Finish" button in edit view. If the user marks a draft as finished or manually finish there draft in edit view, the user will be alerted:

- Title: Draft Finished
- Content: The message is moved from Saved Drafts to Timeline because you finished it.
- Buttons:
  - Left: Don’t Show Again
  - Right (bold): OK

After this alert gets dismissed (or skipped, if previously selected "Don’t Show Again"), the share menu shall appear — whenever a message is finished, the share menu shall appear (unless turned off in settings, which will be implemented later).

**Comment by yisiliu** [comment]
As discussed, we also need to display a filter here for **messages composed in the app** and **messages composed via keyboard**. >>>>>>>Open a new issue to discuss this.

**Comment by Tlaster** [comment]
O.2.5-pre4

**Comment by neruthes** [comment]
Done on both platforms? cc @Tlaster @MainasuK @jk234ert
