### ISSUE TITLE
Introduction Tutorial

### ISSUE THREAD

**Issue by neruthes** [DimensionDev/Tessercube-Meta#6]
With introduction tutorial, we will let the user have an overview of Tessercube, and will ask the user to grant access.

# iOS

![Tutorial - S1](https://user-images.githubusercontent.com/2139261/57213640-f83de080-6fd6-11e9-995a-8c402c17d2ee.png)
![Tutorial - S2](https://user-images.githubusercontent.com/2139261/57213641-f83de080-6fd6-11e9-9a42-58be175774b1.png)
![Tutorial - S3](https://user-images.githubusercontent.com/2139261/57213643-f83de080-6fd6-11e9-9072-650281939aac.png)

# Android

![Tutorial - S1](https://user-images.githubusercontent.com/2139261/57213665-07bd2980-6fd7-11e9-94c0-af76b537ca50.png)
![Tutorial - S2](https://user-images.githubusercontent.com/2139261/57213666-0855c000-6fd7-11e9-9f7f-71220d101dad.png)
![Tutorial - S3](https://user-images.githubusercontent.com/2139261/57213667-0855c000-6fd7-11e9-8546-b050876354b9.png)

# Pictures

![Illustration--GetPublicKeys](https://user-images.githubusercontent.com/2139261/56861659-63adff80-6992-11e9-88a6-6ff20ed20949.png)

![Illustration--TypeAndEncrypt](https://user-images.githubusercontent.com/2139261/56861668-6e689480-6992-11e9-9989-37f210de3faf.png)

![Illustration--CopyToInterpret](https://user-images.githubusercontent.com/2139261/56861671-7a545680-6992-11e9-8bd5-053020dd8774.png)

**Comment by yisiliu** [comment]
**Please add Android support in all the proposals**
--------------------------------------------------------------------
1. What does it mean by "Find Public Keys"?
2. We should also add composition and message management overview.

In addition, we should also add a wizard to let users go over the following procedure:
1. The user needs to import or create their own keys first.
2. Jump to the second (messages) tab to start composing a message
3. Keyboard tutorial should now be triggered at composition.
4. Encrypt to themselves and also sign it themselves.
5. Copy to interpret the message

^This is just an overview - please collaborate on this.

**Comment by Tedko** [comment]
Consider to change the pic of the eye

**Comment by neruthes** [comment]
> ## **Please add Android support in all the proposals**
> 1. What does it mean by "Find Public Keys"?
> 2. We should also add composition and message management overview.
> 
> In addition, we should also add a wizard to let users go over the following procedure:
> 
> 1. The user needs to import or create their own keys first.
> 2. Jump to the second (messages) tab to start composing a message
> 3. Keyboard tutorial should now be triggered at composition.
> 4. Encrypt to themselves and also sign it themselves.
> 5. Copy to interpret the message
> 
> ^This is just an overview - please collaborate on this.

- Android coming soon.
- Elaborate "composition and message management overview", please?
- I recommend considering "wizard" in the next version.

**Comment by yisiliu** [comment]
> * Android coming soon.
DDL: 5/4

> * Elaborate "composition and message management overview", please?
Since this is a tutorial, you have to describe how each tab or functionality works.

> * I recommend considering "wizard" in the next version.
We are pretty close to the "next version". The design is expected before actually implementing that.

**Comment by neruthes** [comment]
[tutorial-images.zip](https://github.com/DimensionDev/Tessercube-Meta/files/3130205/tutorial-images.zip)
![Illustration--TypeAndEncrypt](https://user-images.githubusercontent.com/2139261/56945524-042d2c80-6b17-11e9-8e1f-4676fb7680d6.png)
![Illustration--GetPublicKeys](https://user-images.githubusercontent.com/2139261/56945526-04c5c300-6b17-11e9-9a8d-6fb398cacf65.png)
![Illustration--CopyToInterpret](https://user-images.githubusercontent.com/2139261/56945530-04c5c300-6b17-11e9-8d7a-72624a8a8748.png)

**Comment by yisiliu** [comment]
> * Android coming soon.
@neruthes

**Comment by neruthes** [comment]
The 3rd picture may be changed in current or later version.
