### ISSUE TITLE
Try adding lost payload header & footer, before yielding error

### ISSUE THREAD

**Issue by Tedko** [DimensionDev/Tessercube-Meta#7]

**Comment by neruthes** [comment]
Effective in all importing and interpreting scenarios.

**Comment by Tedko** [comment]
After discussing with @Tlaster and @MainasuK , we need to consider a more specific solution for this

**Comment by neruthes** [comment]
A more sophisticated and more generalized policy set may be introduced in later versions.

**Comment by neruthes** [comment]
Any latest news? cc @Tlaster @MainasuK @jk234ert

**Comment by MainasuK** [comment]
https://github.com/SujiTech/DMS_TesserCube_iOS/issues/15

wontfix

**Comment by neruthes** [comment]
> [SujiTech/DMS_TesserCube_iOS#15](https://github.com/SujiTech/DMS_TesserCube_iOS/issues/15)
> 
> wontfix

👌
